{
  description = "LLM-agnostic agent rules — a Nix catalog of rule files.";

  outputs = { self }:
    let
      root = ./rules;
      rev = self.shortRev or self.rev or "dirty";

      # The naming convention in AGENTS.md (lowercase kebab-case `.md`) is the
      # discovery contract: every compliant rule file in the `rules/` directory
      # joins the catalog; non-rule files (AGENTS.md, README.md, LICENSE,
      # flake.nix, .gitignore) are excluded because they are not lowercase
      # kebab-case.
      ruleRegex = "([a-z][a-z0-9-]*)\\.md";
      isRule = n: builtins.match ruleRegex n != null;
      ruleFiles = builtins.filter isRule (builtins.attrNames (builtins.readDir root));
      nameOf = f: builtins.head (builtins.match ruleRegex f);

      # Stable public API: rule name -> store path of the rule file.
      rules = builtins.listToAttrs (map (f: {
        name  = nameOf f;
        value = root + "/${f}";
      }) ruleFiles);

      # Build a derivation of selected rules. `levels` maps a relative path
      # (e.g. ".", "backend", "backend/api") to an ordered rule set — a map of
      # output basename to rule name. The output is a directory tree that
      # mirrors the level structure: root-level files sit at the top,
      # subdirectories contain their level's rules. Empty levels are skipped.
      # Unknown rule names fail at evaluation time (typo-safe). Each generated
      # file is prefixed with a provenance header recording the source
      # revision, making drift and hand-edits immediately visible.
      materializeRules = pkgs: { levels ? { }, name ? "rules", sentinel ? ".generated" }:
        let
          # Build a single level's rules into a derivation.
          buildLevel = levelPath: ordered:
            let
              entries = builtins.attrValues (builtins.mapAttrs
                (out: rule: { name = "${out}${sentinel}.md"; src = rules.${rule}; })
                ordered);
              copyLines = map (e: ''
                printf '<!-- generated by llm-rules @%s — do not edit -->\n' '${rev}' > "$out/${e.name}"
                printf '\n' >> "$out/${e.name}"
                cat '${e.src}' >> "$out/${e.name}"
              '') entries;
              safeName = builtins.replaceStrings ["/"] ["-"] levelPath;
            in pkgs.runCommand "${name}-${safeName}" { } ''
              mkdir -p "$out"
              ${builtins.concatStringsSep "\n" copyLines}
            '';

          # Only include levels that have at least one rule.
          nonEmptyLevels = builtins.filter
            (levelPath: builtins.attrNames levels.${levelPath} != [])
            (builtins.attrNames levels);

          levelDerivations = builtins.listToAttrs (map (levelPath: {
            name  = levelPath;
            value = buildLevel levelPath levels.${levelPath};
          }) nonEmptyLevels);

          # Assemble the directory tree. Root-level files land at the top;
          # subdirectory levels create nested directories.
          assembleLine = levelPath:
            let drv = levelDerivations.${levelPath};
            in if levelPath == "." then ''
              for f in ${drv}/*; do
                cp "$f" "$out/$(basename "$f")"
              done
            '' else ''
              mkdir -p "$out/${levelPath}"
              for f in ${drv}/*; do
                cp "$f" "$out/${levelPath}/$(basename "$f")"
              done
            '';
        in pkgs.runCommand name { } ''
          mkdir -p "$out"
          ${builtins.concatStringsSep "\n" (map assembleLine nonEmptyLevels)}
        '';

      # Validate that every rule file follows the AGENTS.md format (required
      # headings: title, Scope, Statement, Rationale). Returns a derivation
      # that succeeds if all rules are well-formed and fails with diagnostics
      # otherwise. Wire into your project's `checks` for automated validation.
      lintRules = pkgs: pkgs.runCommand "lint-rules" { } ''
        for rule in ${builtins.concatStringsSep " " (builtins.attrValues rules)}; do
          name=$(basename "$rule" .md)
          grep -q '^# ' "$rule" || { echo "ERROR: $name: missing title heading" >&2; exit 1; }
          grep -q '^## Scope' "$rule" || { echo "ERROR: $name: missing '## Scope' section" >&2; exit 1; }
          grep -q '^## Statement' "$rule" || { echo "ERROR: $name: missing '## Statement' section" >&2; exit 1; }
          grep -q '^## Rationale' "$rule" || { echo "ERROR: $name: missing '## Rationale' section" >&2; exit 1; }
          echo "OK: $name"
        done
        touch $out
      '';
    in {
      inherit rules;
      lib.materializeRules = materializeRules;
      lib.lintRules = lintRules;
    };
}
