{
  description = "LLM-agnostic agent rules — a Nix catalog of rule files.";

  outputs = { self }:
    let
      root = ./.;
      rev = self.shortRev or self.rev or "dirty";

      # The naming convention in AGENTS.md (lowercase kebab-case `.md`) is the
      # discovery contract: every compliant rule file at the repo root joins the
      # catalog; non-rule root files (AGENTS.md, README.md, LICENSE, flake.nix,
      # .gitignore) are excluded because they are not lowercase kebab-case.
      ruleRegex = "([a-z][a-z0-9-]*)\\.md";
      isRule = n: builtins.match ruleRegex n != null;
      ruleFiles = builtins.filter isRule (builtins.attrNames (builtins.readDir root));
      nameOf = f: builtins.head (builtins.match ruleRegex f);

      # Stable public API: rule name -> store path of the rule file.
      rules = builtins.listToAttrs (map (f: {
        name  = nameOf f;
        value = root + "/${f}";
      }) ruleFiles);

      # Build an ordered directory of selected rules. The provider is
      # agent-agnostic: the consumer names the derivation (`name`) and chooses
      # the managed-file marker (`sentinel` -> `<key>${sentinel}.md`). Which
      # workspace directory the rules land in is the consumer's sync concern.
      # `ordered` maps an output basename (e.g. "10-conventional-commits") to a
      # rule name. Unknown names fail at evaluation time (typo-safe). `pkgs` is
      # the consumer's nixpkgs, so this flake stays input-free.
      #
      # Each generated file is prefixed with a provenance header recording the
      # source revision, making drift and hand-edits immediately visible.
      materializeRules = pkgs: { ordered ? { }, name ? "rules", sentinel ? ".generated" }:
        let
          entries = builtins.attrValues (builtins.mapAttrs
            (out: rule: { name = "${out}${sentinel}.md"; src = rules.${rule}; })
            ordered);
          copyLines = map (e: ''
            printf '<!-- generated by llm-rules @%s — do not edit -->\n' '${rev}' > "$out/${e.name}"
            printf '\n' >> "$out/${e.name}"
            cat '${e.src}' >> "$out/${e.name}"
          '') entries;
        in pkgs.runCommand name { } ''
          mkdir -p "$out"
          ${builtins.concatStringsSep "\n" copyLines}
        '';

      # Validate that every rule file follows the AGENTS.md format (required
      # headings: title, Scope, Statement, Rationale). Returns a derivation
      # that succeeds if all rules are well-formed and fails with diagnostics
      # otherwise. Wire into your project's `checks` for automated validation.
      lintRules = pkgs: pkgs.runCommand "lint-rules" { } ''
        for rule in ${builtins.concatStringsSep " " (builtins.attrValues rules)}; do
          name=$(basename "$rule" .md)
          grep -q '^# ' "$rule" || { echo "ERROR: $name: missing title heading" >&2; exit 1; }
          grep -q '^## Scope' "$rule" || { echo "ERROR: $name: missing '## Scope' section" >&2; exit 1; }
          grep -q '^## Statement' "$rule" || { echo "ERROR: $name: missing '## Statement' section" >&2; exit 1; }
          grep -q '^## Rationale' "$rule" || { echo "ERROR: $name: missing '## Rationale' section" >&2; exit 1; }
          echo "OK: $name"
        done
        touch $out
      '';
    in {
      inherit rules;
      lib.materializeRules = materializeRules;
      lib.lintRules = lintRules;
    };
}
